In [2]:
import numpy as np


In [5]:
np.arange(0,10,2)


array([0, 2, 4, 6, 8])

In [6]:
np.eye(2)


array([[1., 0.],
       [0., 1.]])

In [7]:
l = [1,3,4]
np.array(l)


array([1, 3, 4])

In [8]:
np.linspace(0,10,10)


array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [5]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [6]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.ones((2,4))


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
np.random.rand(5)


array([0.8711788 , 0.95814652, 0.93544605, 0.95758161, 0.8398186 ])

In [8]:
np.random.rand(5,5)


array([[0.73956736, 0.89502667, 0.58002787, 0.00832991, 0.02055386],
       [0.16291253, 0.56515249, 0.96359198, 0.0569631 , 0.02065983],
       [0.30046334, 0.81711643, 0.68705213, 0.60757923, 0.23903663],
       [0.86287409, 0.40385826, 0.2499062 , 0.16079762, 0.02480316],
       [0.70664809, 0.60369191, 0.43919651, 0.51989777, 0.86068323]])

In [9]:
np.random.randn(2)


array([0.76848665, 1.57505619])

In [10]:
np.random.randint(1,100)


30

In [21]:
ranarr = np.random.randint(1,100, 10)
ranarr.max()

72

In [17]:
ranarr.min()

3

In [18]:
ranarr.argmax()

2

In [23]:
ranarr.shape

(10,)

In [24]:
ranarr.dtype

dtype('int32')

In [13]:
arr = np.arange(25)


In [25]:
arr.reshape(5,5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
arr.shape


(25,)

In [6]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
arr[8]


8

In [31]:
arr[1:5]


array([1, 2, 3, 4])

In [32]:
arr[0:5]


array([0, 1, 2, 3, 4])

In [33]:
arr[:]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr[:2] = 100
arr


array([100, 100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [9]:
arr_copy = arr.copy()


In [10]:
arr_2d = np.array([[1,2,3], [4,5,6]])


In [11]:
arr_2d[0][1]


2

In [13]:
arr_2d[0,1]


2

In [14]:
arr_2d = np.array([[5,10,15],
                   [20,25,30],
                   [35,40,45]])


In [15]:
arr_2d[1:,:2]


array([[20, 25],
       [35, 40]])

In [17]:
arr = np.arange(1,11)

In [18]:
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
bool_arr = arr > 5


In [20]:
bool_arr


array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [21]:
arr[bool_arr]


array([ 6,  7,  8,  9, 10])

In [22]:
arr[arr > 5]


array([ 6,  7,  8,  9, 10])

In [23]:
arr[arr < 3]


array([1, 2])

In [24]:
arr_2d = np.arange(50).reshape(5,10)


In [25]:
arr_2d


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [26]:
arr_2d[1:3,3:5]


array([[13, 14],
       [23, 24]])

In [27]:
arr_2d.shape


(5, 10)

In [28]:
arr = np.arange(0,11)


In [29]:
arr + arr


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [30]:
arr - arr


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [31]:
arr * arr


array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [32]:
arr + 100


array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [33]:
arr * 100


array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [34]:
arr / arr


C:\Users\Gagan M\AppData\Local\Temp\ipykernel_7460\3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [35]:
 1 / arr


C:\Users\Gagan M\AppData\Local\Temp\ipykernel_7460\4008466510.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [36]:
arr ** 2


array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [37]:
np.sqrt(arr)


array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [38]:
np.exp(arr)


array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [39]:
arr.max()


10

In [40]:
np.sin(arr)


array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [41]:
np.exp(arr)


array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])